import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  startedSidebar: [
    {
      type: "doc",
      label: "Quick Start",
      id: "quickstart",
    },
    {
      type: "doc",
      label: "Installation",
      id: "installation",
    },
  ],
  documentationSidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "introduction",
    },
    {
      type: "autogenerated",
      dirName: "algorithms",
    },
    {
      type: "autogenerated",
      dirName: "environments",
    },
    {
      type: "autogenerated",
      dirName: "hyperparameter-optimization",
    },
    {
      type: "autogenerated",
      dirName: "api",
    },
    {
      type: "autogenerated",
      dirName: "developers",
    },
  ],
};

export default sidebars;
